### ISSUE TITLE
 FileNotFoundError: [Errno 2] No such file or directory: '/private/var/folders/5h/9tzfcvhs36d06wtlk00000gn/T/pip-install-pzjq8p3c/jupiter-python-sdk_30c0824dbb0e41cd9c3a956db90b7b5c/jupiter_python_sdk/README.md'

### ISSUE THREAD

**Issue by shifenhutu** [0xTaoDev/jupiter-python-sdk#1]
system :  macos latest
python: 3.11
pip : 23.1.2 

when i run `pip install jupiter-python-sdk `

i got this error:

```
Looking in indexes: https://mirrors.aliyun.com/pypi/simple/
Collecting jupiter-python-sdk
  Downloading https://mirrors.aliyun.com/pypi/packages/32/be/053abcdb337db09bce91c64ed82def74eac8306ef75d853fb98c1342f9ea/jupiter-python-sdk-0.0.1.1.tar.gz (19 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [8 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/private/var/folders/5h/9tzfcvhs36d06wtlk00000gn/T/pip-install-pzjq8p3c/jupiter-python-sdk_30c0824dbb0e41cd9c3a956db90b7b5c/setup.py", line 7, in <module>
          with codecs.open(os.path.join(here, "jupiter_python_sdk/README.md"), encoding="utf-8") as fh:
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "<frozen codecs>", line 906, in open
      FileNotFoundError: [Errno 2] No such file or directory: '/private/var/folders/5h/9tzfcvhs36d06wtlk00000gn/T/pip-install-pzjq8p3c/jupiter-python-sdk_30c0824dbb0e41cd9c3a956db90b7b5c/jupiter_python_sdk/README.md'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.



```

**Comment by 0xTaoDev** [comment]
Hello, I fixed the issue, you can install it without any problems now, tell me if it's working for you

**Comment by shifenhutu** [comment]
i  got a new error, when i install it


```
 Building wheel for pyaudio (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Building wheel for pyaudio (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [18 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build/lib.macosx-10.9-x86_64-cpython-311
      creating build/lib.macosx-10.9-x86_64-cpython-311/pyaudio
      copying src/pyaudio/__init__.py -> build/lib.macosx-10.9-x86_64-cpython-311/pyaudio
      running build_ext
      building 'pyaudio._portaudio' extension
      creating build/temp.macosx-10.9-x86_64-cpython-311
      creating build/temp.macosx-10.9-x86_64-cpython-311/src
      creating build/temp.macosx-10.9-x86_64-cpython-311/src/pyaudio
      clang -DNDEBUG -fwrapv -O2 -Wall -fPIC -O2 -isystem /Users/a123/.conda/envs/py311_mms/include -fPIC -O2 -isystem /Users/a123/.conda/envs/py311_mms/include -DMACOS=1 -I/usr/local/include -I/usr/include -I/opt/homebrew/include -I/Users/a123/.conda/envs/py311_mms/include/python3.11 -c src/pyaudio/device_api.c -o build/temp.macosx-10.9-x86_64-cpython-311/src/pyaudio/device_api.o
      src/pyaudio/device_api.c:9:10: fatal error: 'portaudio.h' file not found
      #include "portaudio.h"
               ^~~~~~~~~~~~~
      1 error generated.
      error: command '/usr/bin/clang' failed with exit code 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for pyaudio
Successfully built jupiter-python-sdk
Failed to build pyaudio
ERROR: Could not build wheels for pyaudio, which is required to install pyproject.toml-based projects

```

**Comment by 0xTaoDev** [comment]
It should be good now, tell me if it's working

**Comment by shifenhutu** [comment]
thank you  @0xTaoDev 

it's working now  for me
