### ISSUE TITLE
The token  is not tradable

### ISSUE THREAD

**Issue by CRY-D** [0xTaoDev/jupiter-python-sdk#13]
Ah, it's me again ;)
I'm currently facing the following issue: I know it's not the library's issue but the DEX jup aggregator. When I snap a newly created pools on Raydium, roughly within the first 10 to 20 seconds, and then execute the trade, it always returns the message 'The token whatever is not tradable :('. 
 
However, when I search the token address on Dexscreener or Birdeye ... oh my, is already there and tradable :100:.

![Screenshot_20240322_025903](https://github.com/0xTaoDev/jupiter-python-sdk/assets/16564491/07450fe8-5c87-42c6-a7cf-cf4d615cfa66)

**Comment by jglrmm** [comment]
Hello, I have the same issue, have you found any alternative?

**Comment by 0xTaoDev** [comment]
Hello, if I'm not mistaken, once the token met the criterias (token metadata, $250 liquidity buy/sell, price impact below 30%), it will be listed automatically within few minutes.
So that's probably why there is a delay.

Source: https://docs.jup.ag/docs/get-your-token-onto-jup#tokens-with-sufficient-liquidity-and-on-chain-metadata-are-automatically-listed

**Comment by AL-THE-BOT-FATHER** [comment]
> Ah, it's me again ;) I'm currently facing the following issue: I know it's not the library's issue but the DEX jup aggregator. When I snap a newly created pools on Raydium, roughly within the first 10 to 20 seconds, and then execute the trade, it always returns the message 'The token whatever is not tradable :('.
> 
> However, when I search the token address on Dexscreener or Birdeye ... oh my, is already there and tradable 💯.
> 
> ![Screenshot_20240322_025903](https://private-user-images.githubusercontent.com/16564491/315861575-07450fe8-5c87-42c6-a7cf-cf4d615cfa66.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI2NDUyODMsIm5iZiI6MTcxMjY0NDk4MywicGF0aCI6Ii8xNjU2NDQ5MS8zMTU4NjE1NzUtMDc0NTBmZTgtNWM4Ny00MmM2LWE3Y2YtY2Y0ZDYxNWNmYTY2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA5VDA2NDMwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMwZTEwYzhkNGIxODZkNDQ2MzU4MDM5ZDcyMWVlNzUyNTM3YjAxM2NmYmE2ZTAzNmRlMmNhMGJjNjk3YmNjZmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.dAZLd1W_i7Ftbku50vtyrRBZKE7GJFs6AhKewusAmUA)

Jupiter doesn't trade new pairs. You have to use the Raydium SDK.

**Comment by aleph0ne** [comment]
Is there a python Raydium API/SDK? I haven't found one.

**Comment by AL-THE-BOT-FATHER** [comment]
> Is there a python Raydium API/SDK? I haven't found one.

Check this out. 

https://github.com/leq6c/soldexpy

This guy has a **good start** on doing Raydium swaps, but unfortunately the code is super slow, even with a good RPC. This wouldn't be suitable for an production level code, in fact he expressly says that it is experimental.  

If this code could be improved upon, it could be great.

**Comment by nandubatchu** [comment]
Noticed that some of the tokens are available on their private api host: `
https://edge-quote-api.jup.ag` while the same tokens are deemed not tradable on `https://quote-api.jup.ag`

**Comment by alekskravchenko** [comment]
> Noticed that some of the tokens are available on their private api host: ` https://edge-quote-api.jup.ag` while the same tokens are deemed not tradable on `https://quote-api.jup.ag`

Yes, but can't send ".swapPost" to this url. Got:
`  'Program log: panicked at 'range end index 72 out of range for slice of length 0', src/token.rs:537:39',
    'Program JUP6LkbZbjS1jKKwapdHNy74zcZ3tLUZoi5QNyVTaV4 consumed 33807 of 1353845 compute units',
    'Program JUP6LkbZbjS1jKKwapdHNy74zcZ3tLUZoi5QNyVTaV4 failed: SBF program panicked'`

**Comment by bambi-bf** [comment]
When I build transaction including two swap instructions and sol transfer instruction:
"Program log: Instruction: Route"
"Program log: panicked at 'range end index 72 out of range for slice of length 0', src/token.rs:537:39"
"Program JUP6LkbZbjS1jKKwapdHNy74zcZ3tLUZoi5QNyVTaV4 consumed 18729 of 778155 compute units"
"Program JUP6LkbZbjS1jKKwapdHNy74zcZ3tLUZoi5QNyVTaV4 failed: SBF program panicked"

**Comment by sssionggg** [comment]
if you run into `"Program log: panicked at 'range end index 72 out of range for slice of length 0', src/token.rs:537:39"` error, that means that you are missing the necessary token accounts to swap to and from.

this can happen if you are skipping `setupInstructions` if you are using `/swap-instructions`.

**Comment by 0xtrou** [comment]
https://station.jup.ag/guides/general/get-your-token-on-jupiter#how-to-get-your-pool-routed-on-jupiter

Just read it here, I just wondered if there are ways to bypass these criteria?
